default: &default
  adapter: postgresql
  username: psql_user
  password: 123456
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: Suport_Help_DB_dev

test:
  <<: *default
  database: Suport_Help_DB_test

#production:
#  <<: *default
#  database: db/prod.SupportHelpDB
