source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'haml', '~> 4.0.6'
gem 'bootstrap-sass', '~> 3.3.4.1'
gem 'devise', '~> 3.5.0'
gem 'cancancan', '~> 1.10'
gem 'simple_form', '~> 3.1.0'
gem 'pg'
gem "paperclip", '~> 4.2'
gem 'less-rails', '~> 2.7.0'
gem 'therubyracer'
gem 'validates_cpf_cnpj'
gem 'dotiw', github: 'radar/dotiw'
gem 'will_paginate-bootstrap'
gem 'sunspot_rails'
gem 'sunspot_solr'
gem "sunspot_test"
gem 'bootstrap-modal-rails'

group :development, :test do
  gem 'progress_bar'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
  gem 'rspec'
  gem 'haml-rails', '~> 0.9.0'
  gem 'ffaker'
end

group :development do
  gem 'mailcatcher'
  gem 'pry-byebug'
  gem 'better_errors'
end

group :test do
  gem 'guard-rspec'
  gem 'shoulda-matchers'
  gem 'capybara', '~> 2.4.4'
  gem 'capybara-screenshot'
  gem "factory_girl_rails", "~> 4.0"
end
