source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'haml', '~> 4.0.6'
gem 'bootstrap-sass', '~> 3.3.4.1'
gem 'devise', '~> 3.5.0'
gem 'rolify', '~> 4.0.0'
gem 'cancancan', '~> 1.10.1'
gem 'paranoid'
gem 'simple_form', '~> 3.1.0'
gem 'pg'
gem 'sunspot', '~> 2.2.0'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
  gem 'rspec'
  gem 'haml-rails', '~> 0.9.0'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'guard-rspec'
  gem 'factory_girl', '~> 4.5.0'
  gem 'capybara', '~> 2.4.4'
end
