# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b0587095dcbb33d72375bc549c31c94db575195628052c5267512c3a5625b7a74206cd5cdb8c24a4e70168ed552e6a59a3a2a525b0f6f0267e729fab9d083af

test:
  secret_key_base: 409b7e717e2f98658b01868aa7527b628fd1fc4942d1021dbe5ecaea0f84a808232b4b028e2d2e8321caee3304394ea7d11858e0f38ac9e8c1ebf9389f2c0885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
